### ISSUE TITLE
Game Progress Metric

### ISSUE THREAD

**Issue by knightnemo** [cognitiveailab/GPT-simulator#1]
Hello, Great work! I was wondering the metric you used to compute the game progress in table 3 of your paper, is the script to evaluating this metric released? Didn't seem to find it, many thanks!

**Comment by ruoyao-wang** [comment]
Hi, if you run the simulator experiment (quest_gpt.py) and set the argument data_type to score, you should be able to get the game progress results.

**Comment by knightnemo** [comment]
Thank you for your time, solved my problem :)
